// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzhikfwmzzqlsgqygual.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6aGlrZndtenpxbHNncXlndWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDA2OTYsImV4cCI6MjA2Njc3NjY5Nn0.CHks-jQHWuPMDScJa9zZI1e8hbX0APkhCgruv7XLNTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});